//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int cid { get; set; }
        public string cname { get; set; }
        public string cemail { get; set; }
        public string cAddrees { get; set; }
        public string ccity { get; set; }
        public string cnumber { get; set; }
        public string cpassword { get; set; }
        public Nullable<double> clongitude { get; set; }
        public Nullable<double> clattitude { get; set; }
    }
}
