//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dboyrating
    {
        public int ratid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> did { get; set; }
        public Nullable<int> rating { get; set; }
        public string status { get; set; }
    }
}
