//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverBoy
    {
        public int did { get; set; }
        public string dname { get; set; }
        public string daddress { get; set; }
        public string dnumber { get; set; }
        public string dpassword { get; set; }
        public string dbikenumber { get; set; }
        public string dlattitude { get; set; }
        public string dlongitude { get; set; }
        public string demail { get; set; }
        public Nullable<bool> WorkingStatus { get; set; }
    }
}
