//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_item
    {
        public int fid { get; set; }
        public string fname { get; set; }
        public string ftype { get; set; }
        public Nullable<int> fprice { get; set; }
        public Nullable<int> fdiscount { get; set; }
        public Nullable<int> ftime { get; set; }
        public Nullable<int> rid { get; set; }
    
        public virtual Resturant Resturant { get; set; }
    }
}
