//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int mid { get; set; }
        public string Deleiveryday { get; set; }
        public Nullable<System.TimeSpan> dtime { get; set; }
        public string Routinetype { get; set; }
        public string quantity { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<bool> activatestatus { get; set; }
        public Nullable<int> oid { get; set; }
    }
}
