//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FYPEntities : DbContext
    {
        public FYPEntities()
            : base("name=FYPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<Resturant> Resturants { get; set; }
        public virtual DbSet<DeliverBoy> DeliverBoys { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<SubscriptionDeleivery> SubscriptionDeleiveries { get; set; }
        public virtual DbSet<FoodItem> FoodItems { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<returantrating> returantratings { get; set; }
        public virtual DbSet<Dboyrating> Dboyratings { get; set; }
        public virtual DbSet<ordersstatu> ordersstatus { get; set; }
    
        public virtual ObjectResult<scheduledataday_Result> scheduledataday(string ddays)
        {
            var ddaysParameter = ddays != null ?
                new ObjectParameter("ddays", ddays) :
                new ObjectParameter("ddays", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<scheduledataday_Result>("scheduledataday", ddaysParameter);
        }
    
        public virtual ObjectResult<scheduledataday1_Result> scheduledataday1(string ddays)
        {
            var ddaysParameter = ddays != null ?
                new ObjectParameter("ddays", ddays) :
                new ObjectParameter("ddays", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<scheduledataday1_Result>("scheduledataday1", ddaysParameter);
        }
    
        public virtual ObjectResult<scheduledata2_Result> scheduledata2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<scheduledata2_Result>("scheduledata2");
        }
    
        public virtual ObjectResult<ordersproc_Result> ordersproc(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ordersproc_Result>("ordersproc", idParameter);
        }
    }
}
