//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderdid { get; set; }
        public Nullable<int> oid { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<int> foodQantity { get; set; }
        public Nullable<bool> OrderStatus { get; set; }
        public string frating { get; set; }
    }
}
