//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int oid { get; set; }
        public Nullable<System.DateTime> odate { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.TimeSpan> otime { get; set; }
        public Nullable<System.TimeSpan> opickuptime { get; set; }
        public Nullable<System.TimeSpan> odeliverytime { get; set; }
        public Nullable<int> Totalbill { get; set; }
        public Nullable<int> did { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<bool> acceptstatus { get; set; }
        public string status { get; set; }
        public Nullable<int> rid { get; set; }
        public Nullable<bool> SchduleStatus { get; set; }
        public Nullable<System.DateTime> Delivereddate { get; set; }
        public Nullable<bool> activatestatus { get; set; }
        public string schday { get; set; }
    }
}
