//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fypapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionDeleivery
    {
        public int subdelid { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<bool> dstatus { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<int> did { get; set; }
    }
}
